# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 18:22
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, max_length=10)),
                ('quantity', models.IntegerField()),
                ('total_Amount', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_Active', models.BooleanField(default=True)),
                ('picture', models.ImageField(default='img/Basket/default.jpg', upload_to='img/Basket/')),
                ('origin', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_Order', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, max_length=10)),
                ('amount', models.IntegerField()),
                ('date_Submission', models.DateTimeField(auto_now_add=True)),
                ('date_Completed', models.DateTimeField(blank=True, default=None)),
                ('delivery_Amount', models.CharField(max_length=40)),
                ('is_Completed', models.BooleanField(default=False)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KmetApp.Basket')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Selling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_Order', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, max_length=10)),
                ('quantity_Order', models.IntegerField()),
                ('is_Completed', models.BooleanField(default=False)),
                ('date_Submission', models.DateTimeField(auto_now_add=True)),
                ('date_Completed', models.DateTimeField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Selling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, max_length=10)),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_Active', models.BooleanField(default=True)),
                ('picture', models.ImageField(default='img/Selling/default.jpg', upload_to='img/Selling/')),
                ('origin', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('last_Name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=50)),
                ('zip_Code', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('phone_Number', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='selling',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order_selling',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order_selling',
            name='selling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KmetApp.Selling'),
        ),
        migrations.AddField(
            model_name='order_basket',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basket',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
