# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KmetApp', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterField(
            model_name='selling',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, max_length=10),
        ),
    ]
