# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KmetApp', '0004_auto_20170302_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selling',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=5, max_length=10),
        ),
    ]
