# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 11:56
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KmetApp', '0006_auto_20170302_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selling',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, max_length=10),
        ),
    ]
