# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KmetApp', '0007_auto_20170302_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selling',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
