# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KmetApp', '0008_auto_20170303_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='picture',
            field=models.ImageField(default='KmetApp/static/img/Basket/', upload_to='KmetApp/static/img/Basket/'),
        ),
        migrations.AlterField(
            model_name='selling',
            name='picture',
            field=models.ImageField(upload_to='KmetApp/Media/'),
        ),
    ]
