# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KmetApp', '0012_auto_20170317_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='KmetApp/Media/'),
        ),
    ]
