# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KmetApp', '0013_auto_20170324_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_basket',
            old_name='delivery_Amount',
            new_name='frequency',
        ),
        migrations.RenameField(
            model_name='order_basket',
            old_name='amount',
            new_name='quantity_Order',
        ),
    ]
